# Generated by Django 5.0 on 2023-12-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('year', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
