# Generated by Django 5.0 on 2023-12-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car_brand', verbose_name='Марка автомобиля'),
        ),
    ]
