# Generated by Django 5.0 on 2024-01-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Номер VIN'),
        ),
    ]
